live_config_reload = true
[env]
TERM = "xterm-256color"
[shell]
program = "/home/linuxbrew/.linuxbrew/bin/tmux"
[window]
opacity = 0.9
[font]
size = 13.0
# offset.x = -1
[font.normal]
# family = "FiraCode Nerd Font"
family = "Berkeley Mono"
[font.bold]
family = "Berkeley Mono"
[font.italic]
family = "Berkeley Mono"
[font.bold_italic]
family = "Berkeley Mono"
[cursor.style]
shape = "Beam"
blinking = "Never"
[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors= true
[mouse]
hide_when_typing = true
[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = 'CreateNewWindow' },
    { key = "+", mods = "Control|Shift", action = 'IncreaseFontSize' },
    { key = "_", mods = "Control|Shift", action = 'DecreaseFontSize' },
    { key = ")", mods = "Control|Shift", action = 'ResetFontSize' },
]
